# Generated by Django 3.2 on 2023-10-21 11:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20231021_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='_recipes_user_following_+', to=settings.AUTH_USER_MODEL, verbose_name='Подписки'),
        ),
    ]
