# Generated by Django 3.2 on 2023-10-21 13:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20231021_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorite',
        ),
        migrations.AddField(
            model_name='user',
            name='favorite',
            field=models.ManyToManyField(blank=True, to='recipes.Recipe', verbose_name='Избранное'),
        ),
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='_recipes_user_followers_+', to=settings.AUTH_USER_MODEL, verbose_name='Подписчики'),
        ),
    ]
