# Generated by Django 3.2 on 2023-10-21 13:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20231021_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
        migrations.AddField(
            model_name='user',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='_recipes_user_follows_+', to=settings.AUTH_USER_MODEL, verbose_name='Подписки'),
        ),
    ]
