# Generated by Django 3.2 on 2023-10-24 10:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20231021_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipetag',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='recipetag',
            name='tag',
        ),
        migrations.AlterField(
            model_name='user',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL, verbose_name='Подписки'),
        ),
        migrations.DeleteModel(
            name='RecipeIngredient',
        ),
        migrations.DeleteModel(
            name='RecipeTag',
        ),
    ]
